import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <nav className="flex h-14 items-center border-b border-neutral-900 px-6">
        <Link href="/" className="text-lg font-semibold tracking-tight">
          resume.ai
        </Link>
      </nav>
      <article className="max-w-2xl mx-auto px-6 py-12 text-neutral-300 space-y-6">
        <header>
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
          <p className="text-sm text-neutral-500 mt-1">Last updated: 2026-05-23</p>
        </header>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">What this is</h2>
          <p className="text-sm">
            resume.ai is a resume tailoring tool powered by Claude (Anthropic). You give us a job posting and your resume; we generate tailored versions, ATS scores, and related job-hunt material. That&apos;s the whole product.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Your responsibilities</h2>
          <ul className="list-disc pl-5 space-y-2 text-sm">
            <li>Only upload resumes you own. Don&apos;t paste someone else&apos;s.</li>
            <li>Submit real job postings. Pasting random URLs will burn through your runs and degrade output quality.</li>
            <li>Don&apos;t try to bypass our rate limits, IP velocity guards, or other anti-abuse measures.</li>
            <li>Don&apos;t share your account credentials. One human per account.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Our service</h2>
          <ul className="list-disc pl-5 space-y-2 text-sm">
            <li>We try to keep resume.ai running, but this is not a critical service. Outages happen. Plan accordingly.</li>
            <li>We may change pricing. Existing subscribers get 14 days&apos; notice before any price change takes effect.</li>
            <li>We may suspend or terminate accounts that violate the responsibilities above.</li>
            <li>Output is generated by an AI model. It&apos;s a draft, not gospel &mdash; review everything before you send it.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Refunds</h2>
          <p className="text-sm">
            30-day refund guarantee. If you&apos;re not happy with a paid plan within 30 days of purchase, email{" "}
            <a href="mailto:hi@resume.ai" className="underline hover:text-white">
              hi@resume.ai
            </a>{" "}
            and we&apos;ll refund you. No forms, no questions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Liability</h2>
          <p className="text-sm">
            We are not liable for any career outcome &mdash; good or bad &mdash; that results from using resume.ai. We provide a tool. You decide how to use it, what to send, and where to apply. Our total liability to you is capped at what you&apos;ve paid us in the last 12 months.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Governing law</h2>
          <p className="text-sm">
            These terms are governed by the laws of the State of Delaware, USA. Any dispute will be resolved in the state or federal courts located in Delaware.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Contact</h2>
          <p className="text-sm">
            Questions or disputes:{" "}
            <a href="mailto:hi@resume.ai" className="underline hover:text-white">
              hi@resume.ai
            </a>
          </p>
        </section>
      </article>
    </main>
  );
}
