import { SiteNav } from "@/components/layout/SiteNav";
import { SiteFooter } from "@/components/layout/SiteFooter";

/**
 * Terms of service — Apple-light editorial, paired with /privacy.
 */
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#F5F5F7] text-[#1D1D1F]">
      <SiteNav home="/" />

      <article className="mx-auto max-w-2xl px-6 py-16 sm:px-8 sm:py-24">
        <header className="border-b border-[#D2D2D7]/70 pb-8">
          <h1 className="text-h1 text-[#1D1D1F]">Terms of service</h1>
          <p className="mt-3 font-mono text-[13px] tabular-nums text-[#86868B]">
            Last updated · 2026-05-23
          </p>
        </header>

        <div className="mt-12 space-y-12 text-[17px] leading-relaxed text-[#1D1D1F]">
          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">What this is</h2>
            <p className="text-[16px] leading-relaxed text-[#6E6E73]">
              resume.ai is a resume tailoring tool powered by Claude
              (Anthropic). You give us a job posting and your resume; we
              generate tailored versions, ATS scores, and related job-hunt
              material. That&apos;s the whole product.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Your responsibilities</h2>
            <ul className="space-y-3 text-[16px] leading-relaxed text-[#6E6E73]">
              <li>Only upload resumes you own. Don&apos;t paste someone else&apos;s.</li>
              <li>
                Submit real job postings. Pasting random URLs will burn through
                your runs and degrade output quality.
              </li>
              <li>
                Don&apos;t try to bypass rate limits, IP velocity guards, or
                other anti-abuse measures.
              </li>
              <li>
                Don&apos;t share your account credentials. One human per
                account.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Our service</h2>
            <ul className="space-y-3 text-[16px] leading-relaxed text-[#6E6E73]">
              <li>
                We try to keep resume.ai running, but this is not a critical
                service. Outages happen. Plan accordingly.
              </li>
              <li>
                We may change pricing. Existing subscribers get 14 days&apos;
                notice before any price change takes effect.
              </li>
              <li>
                We may suspend or terminate accounts that violate the
                responsibilities above.
              </li>
              <li>
                Output is generated by an AI model. It&apos;s a draft, not
                gospel — review everything before you send it.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Refunds</h2>
            <p className="text-[16px] leading-relaxed text-[#6E6E73]">
              All sales are final. Credits are consumed when a generation
              run starts, which is the moment we incur AI infrastructure
              cost. We don&apos;t refund consumed credits, and we
              don&apos;t refund unused credits &mdash; credits never
              expire, so they sit in your account until you need them. If
              you&apos;re unsure whether resume.ai will work for you, start
              with a Single ($9) before buying a pack. Stripe-side disputes
              and chargebacks are handled per their standard process.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Liability</h2>
            <p className="text-[16px] leading-relaxed text-[#6E6E73]">
              We are not liable for any career outcome — good or bad — that
              results from using resume.ai. We provide a tool. You decide how
              to use it, what to send, and where to apply. Our total liability
              to you is capped at what you&apos;ve paid us in the last 12
              months.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Governing law</h2>
            <p className="text-[16px] leading-relaxed text-[#6E6E73]">
              These terms are governed by the laws of the State of Delaware,
              USA. Any dispute will be resolved in the state or federal courts
              located in Delaware.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-[#1D1D1F]">Contact</h2>
            <p className="text-[16px] leading-relaxed text-[#6E6E73]">
              Questions or disputes:{" "}
              <a
                href="mailto:hi@resume.ai"
                className="text-[#0071E3] underline-offset-4 hover:underline"
              >
                hi@resume.ai
              </a>
              .
            </p>
          </section>
        </div>
      </article>

      <SiteFooter />
    </main>
  );
}
