import { SiteNav } from "@/components/layout/SiteNav";
import { SiteFooter } from "@/components/layout/SiteFooter";

/**
 * Terms of service — same editorial layout as /privacy.
 */
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <SiteNav home="/" />

      <article className="mx-auto max-w-2xl px-6 py-16">
        <header className="border-b border-neutral-900 pb-8">
          <span className="text-[11px] font-semibold uppercase tracking-[0.08em] text-neutral-500">
            Legal
          </span>
          <h1 className="mt-3 text-h1 text-white">Terms of service</h1>
          <p className="mt-2 font-mono text-xs tabular-nums text-neutral-500">
            Last updated · 2026-05-23
          </p>
        </header>

        <div className="mt-12 space-y-10 text-neutral-300">
          <section className="space-y-4">
            <h2 className="text-h2 text-white">What this is</h2>
            <p className="text-sm leading-relaxed text-neutral-400">
              resume.ai is a resume tailoring tool powered by Claude
              (Anthropic). You give us a job posting and your resume; we
              generate tailored versions, ATS scores, and related job-hunt
              material. That&apos;s the whole product.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Your responsibilities</h2>
            <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-neutral-400">
              <li>Only upload resumes you own. Don&apos;t paste someone else&apos;s.</li>
              <li>
                Submit real job postings. Pasting random URLs will burn through
                your runs and degrade output quality.
              </li>
              <li>
                Don&apos;t try to bypass rate limits, IP velocity guards, or
                other anti-abuse measures.
              </li>
              <li>
                Don&apos;t share your account credentials. One human per
                account.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Our service</h2>
            <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-neutral-400">
              <li>
                We try to keep resume.ai running, but this is not a critical
                service. Outages happen. Plan accordingly.
              </li>
              <li>
                We may change pricing. Existing subscribers get 14 days&apos;
                notice before any price change takes effect.
              </li>
              <li>
                We may suspend or terminate accounts that violate the
                responsibilities above.
              </li>
              <li>
                Output is generated by an AI model. It&apos;s a draft, not
                gospel — review everything before you send it.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Refunds</h2>
            <p className="text-sm leading-relaxed text-neutral-400">
              30-day refund guarantee. If you&apos;re not happy with a paid
              plan within 30 days of purchase, email{" "}
              <a
                href="mailto:hi@resume.ai"
                className="text-white underline decoration-neutral-700 underline-offset-4 transition-colors hover:decoration-white"
              >
                hi@resume.ai
              </a>{" "}
              and we&apos;ll refund you. No forms, no questions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Liability</h2>
            <p className="text-sm leading-relaxed text-neutral-400">
              We are not liable for any career outcome — good or bad — that
              results from using resume.ai. We provide a tool. You decide how
              to use it, what to send, and where to apply. Our total liability
              to you is capped at what you&apos;ve paid us in the last 12
              months.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Governing law</h2>
            <p className="text-sm leading-relaxed text-neutral-400">
              These terms are governed by the laws of the State of Delaware,
              USA. Any dispute will be resolved in the state or federal courts
              located in Delaware.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-h2 text-white">Contact</h2>
            <p className="text-sm leading-relaxed text-neutral-400">
              Questions or disputes:{" "}
              <a
                href="mailto:hi@resume.ai"
                className="text-white underline decoration-neutral-700 underline-offset-4 transition-colors hover:decoration-white"
              >
                hi@resume.ai
              </a>
            </p>
          </section>
        </div>
      </article>

      <SiteFooter />
    </main>
  );
}